version: '3.8'

services:
  alpasec-terminal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alpasec-terminal
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80